name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  setup-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https apt-utils ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce

      - name: Build Create Service Docker Image
        run: |
          cd Assignment5_CI_CD/flask_blog_create
          docker build -t create-service .

      - name: Build Read Service Docker Image
        run: |
          cd Assignment5_CI_CD/flask_blog_read
          docker build -t read-service .

      - name: Build Update Service Docker Image
        run: |
          cd Assignment5_CI_CD/flask_blog_update
          docker build -t update-service .

      - name: Build Delete Service Docker Image
        run: |
          cd Assignment5_CI_CD/flask_blog_delete
          docker build -t delete-service .

      - name: Build UI Service Docker Image
        run: |
          cd Assignment5_CI_CD/flask_blog_ui
          docker build -t ui-service .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Push Create Service Image to Docker Hub
        run: |
          docker tag create-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/create-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/create-service:latest

      - name: Push Read Service Image to Docker Hub
        run: |
          docker tag read-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/read-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/read-service:latest

      - name: Push Update Service Image to Docker Hub
        run: |
          docker tag update-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/update-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/update-service:latest

      - name: Push Delete Service Image to Docker Hub
        run: |
          docker tag delete-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/delete-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/delete-service:latest